In [58]:
import pandas as pd
df = pd.read_csv("../data/dataset_100k.csv")

C:\Users\Anandakrishnan VB\AppData\Local\Temp\ipykernel_5736\2622600682.py:2: DtypeWarning: Columns (0: mirror_url) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/dataset_100k.csv")

In [59]:
df.shape

(100000, 83)

In [60]:
df.columns

Index(['id', 'node_id', 'name', 'full_name', 'private', 'owner', 'html_url',
       'description', 'fork', 'url', 'forks_url', 'keys_url',
       'collaborators_url', 'teams_url', 'hooks_url', 'issue_events_url',
       'events_url', 'assignees_url', 'branches_url', 'tags_url', 'blobs_url',
       'git_tags_url', 'git_refs_url', 'trees_url', 'statuses_url',
       'languages_url', 'stargazers_url', 'contributors_url',
       'subscribers_url', 'subscription_url', 'commits_url', 'git_commits_url',
       'comments_url', 'issue_comment_url', 'contents_url', 'compare_url',
       'merges_url', 'archive_url', 'downloads_url', 'issues_url', 'pulls_url',
       'milestones_url', 'notifications_url', 'labels_url', 'releases_url',
       'deployments_url', 'created_at', 'updated_at', 'pushed_at', 'git_url',
       'ssh_url', 'clone_url', 'svn_url', 'homepage', 'size',
       'stargazers_count', 'watchers_count', 'language', 'has_issues',
       'has_projects', 'has_downloads', 'has_wiki', 'has_pages',
       'has_discussions', 'forks_count', 'mirror_url', 'archived', 'disabled',
       'open_issues_count', 'license', 'allow_forking', 'is_template',
       'web_commit_signoff_required', 'has_pull_requests',
       'pull_request_creation_policy', 'topics', 'visibility', 'forks',
       'open_issues', 'watchers', 'default_branch', 'permissions', 'score'],
      dtype='str')

In [61]:
df.head(1)

,id,node_id,name,full_name,private,owner,html_url,description,fork,url,...,has_pull_requests,pull_request_creation_policy,topics,visibility,forks,open_issues,watchers,default_branch,permissions,score
0,1136718169,R_kgDOQ8DxWQ,bmad-assist,Pawel-N-pl/bmad-assist,False,"{'login': 'Pawel-N-pl', 'id': 255624086, 'node...",https://github.com/Pawel-N-pl/bmad-assist,⚠️ Deprecated & unmaintained. This tool only e...,False,https://api.github.com/repos/Pawel-N-pl/bmad-a...,...,True,all,[],public,24,10,100,master,"{'admin': False, 'maintain': False, 'push': Fa...",1.0

In [62]:
keep = ["id", "full_name", "description", "topics", "language",
        "stargazers_count", "forks_count", "created_at", "pushed_at",
        "fork", "archived"]
repos = df[keep].copy()

In [63]:
repos = repos[(repos['fork'] == False) & (repos['archived'] == False)]

In [64]:
repos.shape

(91458, 11)

In [65]:
repos = repos.drop(columns=["fork","archived"])

In [73]:
repos.shape

(86794, 9)

In [79]:
repos.isna().sum()

id                  0
full_name           0
description         0
topics              0
language            0
stargazers_count    0
forks_count         0
created_at          0
pushed_at           0
dtype: int64

In [ ]:
repos["description"] = repos["description"].fillna("")

In [72]:
repos = repos[repos["description"].str.len() > 0]

In [76]:
repos[repos['language'].isna()]

,id,full_name,description,topics,language,stargazers_count,forks_count,created_at,pushed_at
632,383105042,goldenhairs/backtrader_fund,基于akshare和backtrader的回测。,[],NaN,100,30,2021-07-05T10:40:47Z,2021-07-02T15:20:07Z
5482,760942506,berlin29ke/gifted-bot-md,"Hi there, this is 𝗚𝗶𝗳𝘁𝗲𝗱-𝗕𝗼𝘁-𝗠𝗱. Your All-in-O...",[],NaN,99,289,2024-02-21T00:07:42Z,2024-03-22T07:02:09Z
10352,310754887,huaji233333/tiktok_source,Full source code to the android tiktok app.,[],NaN,97,53,2020-11-07T02:57:19Z,2023-03-30T23:54:00Z
14001,362588821,djmuratb/BitCrack2,Brute force Bitcoin private keys.,[],NaN,100,52,2021-04-28T19:47:49Z,2021-04-16T17:25:10Z
14887,234508491,wwg88888888/WeChatExt,WeChatExt是一个基于微信PC hook的项目，可实现微信PC端大部分功能自动化。,[],NaN,96,67,2020-01-17T08:49:19Z,2020-04-28T13:19:30Z
15471,412514772,hottabxp/re3,"GTA III, Vice City",[],NaN,457,307,2021-10-01T15:10:54Z,2024-05-12T10:12:54Z
18392,22803930,JMQCode/iBooks,android平台的电子阅读器，在Google Play下载量50W＋，不过因为账号封号了，...,[],NaN,99,69,2014-08-10T07:17:17Z,2015-06-29T03:33:47Z
18643,1273429520,ahmadkamal09999-tech/usbliter8,An A12/A13 SecureROM exploit,[],NaN,97,256,2026-06-18T14:11:06Z,2026-06-18T12:30:50Z
18813,21861218,aspone/OrderBook,C++ low-latency in-memory order book,[],NaN,96,41,2014-07-15T13:44:13Z,2013-11-17T16:01:21Z
18918,230258035,hail33/ANDRAX-Mobile-Pentest,ANDRAX Advanced Penetration Testing Platform f...,[],NaN,95,125,2019-12-26T12:09:46Z,2023-01-11T21:31:05Z
19240,822546559,zgzhang/cve-2024-6387-poc,a signal handler race condition in OpenSSH's s...,[],NaN,497,185,2024-07-01T10:55:29Z,2024-07-01T10:54:02Z
19977,24717032,yusong-shen/mooc_os_lab,OS Labs for MOOC,[],NaN,425,201,2014-10-02T11:54:51Z,2014-09-28T16:25:20Z
20151,209358265,adspro15/km-um-communication,A somewhat wide collection of various kernelmo...,[],NaN,410,147,2019-09-18T16:44:19Z,2019-09-18T07:15:39Z
22555,1272090157,lyyxqg-lyy/suanle-me,算了么命理工具包,[],NaN,100,74,2026-06-17T09:26:09Z,2026-06-16T09:59:29Z
32329,328827698,Salt69/HS-Grabber,An discord token grabber / stealer stole disco...,[],NaN,95,89,2021-01-12T00:29:06Z,2021-01-11T12:42:39Z
36160,1315829821,k1ngbanana/aipocket,一起打野！基于 FOFA、Shodan 与 GitHub Artifact Hunter，自...,[],NaN,94,261,2026-07-29T07:28:46Z,2026-07-29T06:14:13Z
46840,226614111,xuhaoyang/ClashForAndroid,A rule-based tunnel for Android.,[],NaN,2797,6327,2019-12-08T04:27:53Z,2023-11-03T06:14:40Z
47208,286491417,babyaries/V2rayU,"V2rayU,基于v2ray核心的mac版客户端,用于科学上网,使用swift编写,支持vm...",[],NaN,98,76,2020-08-10T14:04:12Z,2020-05-30T00:19:57Z
47294,1262244463,muftiarfan/noop,Offline WHOOP companion — pair your strap over...,[],NaN,96,1098,2026-06-07T18:51:42Z,2026-06-07T18:32:34Z
47353,626382448,dhamaniasad/cytev2,MacOS background screen recorder/reader for ea...,[],NaN,95,44,2023-04-11T11:05:22Z,2023-04-11T10:54:38Z
60308,10870090,ipopov/starttls-mitm,A starttls-capable transparent man-in-the-midd...,[],NaN,52,10,2013-06-22T18:08:13Z,2014-03-18T22:30:35Z
62065,20010531,Jach/radar_sar_rma,A Python implementation of the Range Migration...,[],NaN,66,16,2014-05-21T06:34:10Z,2014-05-21T09:08:43Z
63010,26061673,jeromeku/Python-Financial-Tools,Providing financial analysis tools to the Pyth...,[],NaN,68,35,2014-11-01T20:01:52Z,2014-02-28T19:51:15Z
63177,21962940,GalvanizeDataScience/Opinion-Mining-Project,Feature-Based Sentiment Analysis in Python,[],NaN,60,40,2014-07-18T01:00:41Z,2014-07-17T22:41:25Z
73164,211292135,Foxgeek36/ZhihuSpider,知乎爬虫，可以爬取知乎上特定问题下的所有回答、单个回答，特定用户的所有回答、文章，话题精华，...,[],NaN,79,57,2019-09-27T10:11:47Z,2019-09-27T09:23:02Z
73223,213119069,CreativeMayhem/CallMeMaybe,Automated System for Spoofing Calls and Brute ...,[],NaN,77,16,2019-10-06T06:25:54Z,2019-09-28T00:58:36Z
74420,314497142,atomat/10jqka-API,同花顺股票交易接口,[],NaN,94,61,2020-11-20T08:51:36Z,2020-07-30T02:30:18Z
74697,290676646,F-Society-Freaks/TikTok-Viewbot,Sends TikTok Views to a video of choice.,[],NaN,87,55,2020-08-27T04:38:23Z,2020-08-26T18:02:08Z
75152,289240924,zehuachenImperial/SkipConvNet,Speech Dereverberation using Fully Convolution...,[],NaN,77,41,2020-08-21T10:20:55Z,2020-08-18T07:01:48Z
75338,354275176,Jyukai02/Gated-Transformer-on-MTS-1,使用改良的Transformer模型应用于多维时间序列的分类任务上,[],NaN,95,15,2021-04-03T11:33:09Z,2021-04-03T11:33:18Z
76991,432614506,stephan-who/DRL_to_DFJSP,this repository is used to reappear thesis《Dyn...,[],NaN,77,22,2021-11-28T04:03:48Z,2021-09-22T07:13:29Z
77129,505781735,xiaogdgenuine/Manga-Colorization-FJ,An amazing manga comic colorization project | ...,[],NaN,98,18,2022-06-21T09:46:50Z,2022-06-21T07:29:02Z
77585,499547955,Qinqing1999/yolov5-tensorrt-aimbot,FPS game AI aimassist framework,[],NaN,86,26,2022-06-03T14:46:36Z,2022-05-29T08:00:01Z
77683,479727438,bruinxiong/EG3D-pytorch,"unofficial code of the paper ""Efficient Geomet...",[],NaN,84,21,2022-04-09T13:00:32Z,2022-04-09T12:31:41Z
77710,506849499,KerryManson/SMSbomb,About 短信轰炸/短信测压/ | 一个健壮免费的python短信轰炸程序，专门炸坏蛋蛋，...,[],NaN,84,20,2022-06-24T02:10:47Z,2022-06-16T02:49:51Z
77877,476656553,jamosnet/JD-comments-sentiment-analysis,利用Python网络爬虫对京东商城中指定商品下的用户评论进行爬取，对数据预处理操作后进行文本...,[],NaN,80,13,2022-04-01T09:28:08Z,2022-03-15T03:39:34Z
78537,515188759,yyds-xtt/DRL-Based-Long-Term-Resource-Planning,"Paper publised in TNSM entitled ""DRL-Based Lon...",[],NaN,84,13,2022-07-18T13:08:31Z,2022-07-18T11:39:05Z
78892,565357201,35plus/FP-Browser-Public,开源免费的移动端指纹浏览器，可编程浏览器底层动态注入，免费创建无限制不同型号手机浏览器测试环境。,[],NaN,75,14,2022-11-13T06:03:42Z,2022-11-11T05:39:30Z
78957,519956287,iloveai8086/YOLOC,🚀🚀🚀YOLOC is Combining different modules to bui...,[],NaN,74,33,2022-08-01T03:53:46Z,2022-07-31T07:58:34Z
81619,801356847,KytraScript/SakugaDataset,Official Repository for Sakuga-42M Dataset,[],NaN,83,10,2024-05-16T04:36:08Z,2024-05-16T00:38:37Z
81671,744966634,KevinLee752/GaussianAvatars,"Official repo for ""GaussianAvatars: Photoreali...",[],NaN,82,39,2024-01-18T11:20:13Z,2024-01-17T13:46:56Z
82799,850073423,m7md2007/Worm-GPT,WormGPT is a malicious AI tool promoted on the...,[],NaN,77,35,2024-08-30T20:32:28Z,2024-04-29T07:28:42Z
83373,969917493,alanhzw/PyWxDump,获取微信信息；读取数据库，本地查看聊天记录并导出为csv、html等格式用于AI训练，自动回...,[],NaN,88,61,2025-04-21T06:31:29Z,2025-03-20T00:32:16Z
84882,1197252744,chensunlai/claude-code-instructkr,An independent Python feature port of Claude Code,[],NaN,97,115,2026-03-31T12:47:59Z,2026-04-05T12:43:19Z
84910,1153355371,Qiyd81/moneyclaw-py,7x24 AI Agent that saves and makes money auton...,[],NaN,96,51,2026-02-09T07:48:56Z,2026-02-09T03:01:42Z
86247,1370727152,flybook-git/flm,Train and chat with a frozen language model co...,[],NaN,71,13,2026-09-15T01:22:11Z,2026-09-11T21:51:26Z

In [77]:
repos["language"] = repos["language"].fillna("")
repos = repos[repos["language"].str.len() > 0]

In [78]:
repos.shape

(86748, 9)

In [96]:
repos = repos[repos["topics"] != "[]"]

In [98]:
repos.shape

(45366, 9)

In [99]:
repos.to_csv("../data/goodset.csv",index=False)

In [1]:
import pandas as pd
df = pd.read_csv("../data/goodset.csv")

In [2]:
df.shape

(45366, 9)

In [6]:
print(df.isna().sum())                      # should be 0 for description
print((df["description"].str.len() == 0).sum())   # should be 0
print(df["id"].is_unique)              # should be True
print(df["stargazers_count"].describe())               # look at the spread

id                  0
full_name           0
description         0
topics              0
language            0
stargazers_count    0
forks_count         0
created_at          0
pushed_at           0
dtype: int64
0
True
count     45366.000000
mean       3213.917868
std       10875.783559
min          12.000000
25%          96.000000
50%         442.000000
75%        1908.000000
max      481529.000000
Name: stargazers_count, dtype: float64